// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXk12ja9_QeUG-Zqfkr4462ho4imGL26E',
    appId: '1:1050910911116:web:a8085171dc7421ed9669a9',
    messagingSenderId: '1050910911116',
    projectId: 'first-app-bc8fc',
    authDomain: 'first-app-bc8fc.firebaseapp.com',
    storageBucket: 'first-app-bc8fc.firebasestorage.app',
    measurementId: 'G-4EN028FES5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQKAe_BUm4gGjHKdQ9yu4qrYvHoxg8J9I',
    appId: '1:1050910911116:android:c989241ab9d96e249669a9',
    messagingSenderId: '1050910911116',
    projectId: 'first-app-bc8fc',
    storageBucket: 'first-app-bc8fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5O4mdolbviogbNvbPfDmOGY4JeCWvzc',
    appId: '1:1050910911116:ios:bd8a9d92eb82c8bc9669a9',
    messagingSenderId: '1050910911116',
    projectId: 'first-app-bc8fc',
    storageBucket: 'first-app-bc8fc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5O4mdolbviogbNvbPfDmOGY4JeCWvzc',
    appId: '1:1050910911116:ios:bd8a9d92eb82c8bc9669a9',
    messagingSenderId: '1050910911116',
    projectId: 'first-app-bc8fc',
    storageBucket: 'first-app-bc8fc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXk12ja9_QeUG-Zqfkr4462ho4imGL26E',
    appId: '1:1050910911116:web:23adb808fe74b2fe9669a9',
    messagingSenderId: '1050910911116',
    projectId: 'first-app-bc8fc',
    authDomain: 'first-app-bc8fc.firebaseapp.com',
    storageBucket: 'first-app-bc8fc.firebasestorage.app',
    measurementId: 'G-163913VCVF',
  );
}
